query GetMember {
  members {
    ...MemberFields
  }
}

mutation CreateMember($input: MemberInput!) {
  createMember(input: $input) {
    ...MemberFields
  }
}

fragment MemberFields on Member {
  id
  nickname
  role
}