type Member {
  id: ID!
  nickname: String!
  role: String!
  firstName: String
  lastName: String
  catchCopy: String
  imageUrl: String
}

type Thumbnail {
  id: ID!
  src: String!
  alt: String!
}

type Blog {
  id: ID!
  url: String!
  date: String!
  category: String!
  title: String!
  writer: Member!
  tags: [String]
  thumbnail: Thumbnail
}

input MemberInput {
  nickname: String!
  role: String!
  firstName: String
  lastName: String
  catchCopy: String
  imageUrl: String
}

type Mutation {
  createMember(input: MemberInput!): Member
}

type Query {
  members: [Member]
  blogs: [Blog]
}
